CREATE DATABASE jwt_db;

DROP TABLE IF EXISTS USERS;

CREATE TABLE users (
  UID SERIAL PRIMARY KEY,
  EMAIL VARCHAR(50) NOT NULL UNIQUE,
  PASSWORD VARCHAR(60) NOT NULL,
  USERNAME VARCHAR(50) NOT NULL
);

INSERT INTO USERS (EMAIL,PASSWORD,USERNAME)
VALUES  ('tester@test.com','tester','tester'),
        ('admin@admin.com', 'admin', 'admin');

SELECT * FROM USERS;